---
- name: 'Add an Apt signing key for docker repository'
  apt_key:
    url: 'https://download.docker.com/linux/ubuntu/gpg'
    state: present

- name: 'Add docker repository'
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'

- name: 'Install docker packages'
  apt:
    name: '{{ item }}'
    state: present
  loop:
    - 'docker-ce'  
    - 'docker-ce-cli' 
    - 'containerd.io'

- name: 'Start docker service'
  systemd: 
    name: 'docker'
    daemon_reload: true
    state: started
    enabled: true
